apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (d48ae64)
  creationTimestamp: null
  labels:
    io.kompose.service: gw
  name: gw
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gw
    spec:
      containers:
      - env:
        - name: ENDPOINT_HOST
          value: :8080
        - name: LOGIC_ADDRESS
          value: logic:9090
        image: gw:latest
        name: gw
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
